### ISSUE TITLE
NameError: name 'ast' is not defined

### ISSUE THREAD

**Issue by HappyDay-design** [Summer142857/unsignalized-junction-control#1]
Hello
Thank you for sharing your code
I had errors when running

Traceback (most recent call last):
  File "/home/osboxes/Desktop/unsignalized-junction-control/diffDemand.py", line 58, in <module>
    data_once = simOnce(np.around(i, 3), plan_controller)
  File "/home/osboxes/Desktop/unsignalized-junction-control/diffDemand.py", line 35, in simOnce
    controller.simOneStep()
  File "/home/osboxes/Desktop/unsignalized-junction-control/Controller/BacisPlanning.py", line 284, in simOneStep
    orders = self.treeGenerate()
  File "/home/osboxes/Desktop/unsignalized-junction-control/Controller/BacisPlanning.py", line 92, in treeGenerate
    label_result = self.safeLabel(self.tree.legal_orders())
  File "/home/osboxes/Desktop/unsignalized-junction-control/Controller/BacisPlanning.py", line 83, in safeLabel
    return [ast.literal_eval(item) for item in tmp_list]
  File "/home/osboxes/Desktop/unsignalized-junction-control/Controller/BacisPlanning.py", line 83, in <listcomp>
    return [ast.literal_eval(item) for item in tmp_list]
NameError: name 'ast' is not defined

**Comment by AntonioAlgaida** [comment]
Hi,

ast is a native library of python:
[Link to ast](https://docs.python.org/3/library/ast.html#ast.literal_eval)

[ast.literal_eval](https://docs.python.org/3/library/ast.html#ast.literal_eval) raises an exception if the input isn't a valid Python datatype, so the code won't be executed if it's not.

Best,

**Comment by HappyDay-design** [comment]
> Hi,
> 
> ast is a native library of python: [Link to ast](https://docs.python.org/3/library/ast.html#ast.literal_eval)
> 
> [ast.literal_eval](https://docs.python.org/3/library/ast.html#ast.literal_eval) raises an exception if the input isn't a valid Python datatype, so the code won't be executed if it's not.
> 
> Best,

Thank you for your reply. Do you know how to debug this model?

**Comment by Summer142857** [comment]
> 

Hi, thanks for your attention to this work. Actually, the implementation of planning-based strategy in this project need to spend a lot of time to traverse all the solutions. So I don't recommend you to use it. 

You can refer to (Li L, Wang F (2006) Cooperative driving at blind crossings using intervehicle communication. IEEE Transactions on Vehicular Technology 55(6):1712-1724, DOI: 10.1109/TVT.2006.878730) for the original ideas of this code.

You can also refer to (https://www.hindawi.com/journals/jat/2022/6653598/) for the idea to reduce the computation time of the planning-based strategy.

Maybe you can state your research purpose and I could give you some advices for your code.

**Comment by JiaxiangZhu** [comment]
You can just import ast
